version: '2'

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=weblib
      - POSTGRES_PASSWORD=football
      - POSTGRES_DB=players
      - PGDATA=/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/pgdata
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./server:/server
      - /server/node_modules

volumes:
  pgdata:
